### ISSUE TITLE
Not supported for Xcode 17 beta

### ISSUE THREAD

**Issue by kusumarakesh** [tayloraswift/swift-png#70] opened 2024-07-07 07:11 UTC
Unfortunately the sdk is not compiling for Xcode 17

<img width="1704" alt="Screenshot 2024-07-07 at 12 41 02 PM" src="https://github.com/tayloraswift/swift-png/assets/103421485/18ac7cd1-97f7-4083-8ede-a02f66fb1859">

**Comment by tayloraswift** [comment] 2024-07-07 20:20
looks like a duplicate of #68

**Closed** 2024-07-07 20:30 UTC

**Comment by kusumarakesh** [comment] 2024-07-08 10:13
Thanks @tayloraswift
